gyro_gain : 0.25

foot_roll_angle_gain : -0.25
foot_pitch_angle_gain : -0.25

foot_roll_angle_time_constant : 1.0
foot_pitch_angle_time_constant : 1.0

left_foot_force_x_gain : 0.05
left_foot_force_y_gain : 0.05

left_foot_force_x_time_constant : 1.0
left_foot_force_y_time_constant : 1.0

right_foot_force_x_gain : 0.05
right_foot_force_y_gain : 0.05

right_foot_force_x_time_constant : 1.0
right_foot_force_y_time_constant : 1.0

foot_force_z_gain : -0.017

foot_force_z_time_constant : 1.0

left_foot_torque_roll_gain : 0.0018
left_foot_torque_pitch_gain : 0.0012

left_foot_torque_roll_time_constant : 1.0
left_foot_torque_pitch_time_constant : 1.0

right_foot_torque_roll_gain : 0.0018
right_foot_torque_pitch_gain : 0.0012

right_foot_torque_roll_time_constant : 1.0
right_foot_torque_pitch_time_constant : 1.0

wb_pelvis_diff_x_constant : -0.15
wb_pelvis_diff_y_constant : -0.09
wb_pelvis_diff_z_constant : 0.2

wb_pelvis_x_max : 0.1
wb_pelvis_x_min : -0.12
wb_pelvis_y_max : 0.05
wb_pelvis_y_min : -0.05
wb_pelvis_z_max : 0.75
wb_pelvis_z_min : 0.3
