# defines joints to be controlled by ros control module
joints:
  ["head_p",
   "head_y",
   "torso_y", 
   "l_arm_sh_p1",
   "l_arm_sh_r",
   "l_arm_sh_p2",
   "l_arm_el_y",
   "l_arm_wr_r",
   "l_arm_wr_y",
   "l_arm_wr_p",
   "r_arm_sh_p1",
   "r_arm_sh_r",
   "r_arm_sh_p2",
   "r_arm_el_y",
   "r_arm_wr_r",
   "r_arm_wr_y",
   "r_arm_wr_p",
   "l_leg_hip_y",
   "l_leg_hip_r",
   "l_leg_hip_p",
   "l_leg_kn_p",
   "l_leg_an_r",
   "l_leg_an_p",
   "r_leg_hip_y",
   "r_leg_hip_r",
   "r_leg_hip_p",
   "r_leg_kn_p",
   "r_leg_an_r",
   "r_leg_an_p"]

# defines which ft sensors to be interfaced
ft_sensors:
  l_foot: ["l_foot", "l_foot_ft_link"]
  r_foot: ["r_foot", "r_foot_ft_link"]
